### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by reflexLabs** [joeattardi/picmo#217] opened 2022-07-23 13:46 UTC
Hey,
Lately I found an issue that cause the scrollable div that contains the categories and emojis to be opened (at the second time and so on) when the scrollbar is in the bottom, i tried to scrollTop with js to the class `EmojiArea_emojis__L4mMq` but it's doesn't work, so i wondering what's the best approach to fix it?

thanks!

**Comment by joeattardi** [comment] 2022-07-23 15:40
I'm not sure what you mean, do you have an example I can look at?

**Comment by reflexLabs** [comment] 2022-07-25 11:57
When I open the emoji picker for the first time (since the load of the page) it's works perfectly,
but then when I close the picker and open again, it's opening the picker but at the bottom of the scrollable container,
that means people can't see the top of the picker like search bar and frequently used emojis but the bottom (some letters emoji)

**Comment by joeattardi** [comment] 2022-07-25 18:20
Can you create a codepen or a simple git repo showing the problem? Sounds like it might be a tricky to reproduce edge case.

**Comment by joeattardi** [comment] 2022-07-31 03:34
Following up, can you provide some sample code?

**Comment by reflexLabs** [comment] 2022-07-31 10:39
> 

Hey, I can share with you the whole project if you up to, I think there's more than 1 file to this issue that needs to be investigated, and I don't want to take your time so let me know (:

**Comment by joeattardi** [comment] 2022-08-01 02:46
Can you create a simplified test case that exhibits the same behavior, or at least a video showing the behavior?

If I'm understanding correctly, you're using a popup picker, when you open it the first time it's ok but after that it opens with the content scrolled down to the bottom?

Using the standard popup picker demo here (https://picmojs.com/storybook/?path=/story/popup-emoji-picker--native) I can't reproduce this. If I open the picker, scroll down to the bottom, then close it and re-open it, the scroll position is correctly reset to the top.

I don't need to see your whole project but can you at least show me the code you're using to create the picker? What would be most helpful is if you can get a CodePen or something exhibiting the issue.

**Closed** 2022-08-12 11:40 UTC
Labels: more info needed
